//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDB_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumList
    {
        public string AlbumName { get; set; }
        public string Artist { get; set; }
        public System.DateTime ReleaseYear { get; set; }
        public string Genre { get; set; }
    }
}
