//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDB_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistView
    {
        public string PlaylistName { get; set; }
        public Nullable<int> TrackCount { get; set; }
        public Nullable<decimal> PlaylistDuration { get; set; }
        public int Id { get; set; }
    }
}
